#!/bin/sh

device=/dev/mmcblk0

sfdisk --force --no-reread --in-order --Linux --unit S ${device} <<-__EOF__
8192,,,-
__EOF__

# The existence of this file triggers a filesystem resize on the next reboot
touch /var/local/resize-rootfs

echo
echo "Reboot to complete filesystem resize"
